### ISSUE TITLE
Visa Card 13 Digits Not Validating

### ISSUE THREAD

**Issue by mhmzdev** [cholojuanito/credit_card_validator#15]
Visa Card with 13 digits are not validating here:

Try VISA: 4222-2222-2222-2
Link: https://www.paypalobjects.com/en_AU/vhelp/paypalmanager_help/credit_card_numbers.htm

Below is a testing sample:

![Screenshot 2023-03-02 at 1 54 33 PM](https://user-images.githubusercontent.com/43790152/222379541-6d60ae37-c3f5-4592-9d05-7e0158c7878e.png)

**Comment by cholojuanito** [comment]
That doesn't really seem like an official PayPal URL. Here's what I see as the valid test cards with them, https://developer.paypal.com/tools/sandbox/card-testing/

This does bring up a good idea of allowing for custom card types or allow editing of the built in card types so that I don't have to put in support for every possible card type out there. I'll probably work on that refactor

**Comment by mhmzdev** [comment]
It just an example I share
VISA 13 digit is an official card being used around
I shared the link to try a card number I didn't claim whether its an official link or not

**Comment by cholojuanito** [comment]
I understand. I'll keep close this issue in favor of the new one I made in the credit_card_type_detector repo that allows for creating custom card types or modifying the built-in card types

**Comment by mhmzdev** [comment]
Understood
